/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/v3oJh0gR6dK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Layout() {
  return (
    <main className="flex flex-col min-h-[100dvh]">
      <section className="w-full pt-12 md:pt-24 lg:pt-32">
        <div className="container space-y-10 xl:space-y-16">
          <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">Sophia Designs</h1>
                <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                  Crafting visually stunning and user-centric designs that captivate and inspire.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#"
                >
                  View Portfolio
                </Link>
              </div>
            </div>
            <img
              alt="Hero"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
              height="550"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Sophia's Best Work</h2>
              <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Explore a selection of Sophia's most captivating and award-winning designs.
              </p>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 md:grid-cols-3 lg:gap-12">
            <div className="group relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Project</span>
              </Link>
              <img
                alt="Project 1"
                className="mx-auto aspect-video overflow-hidden rounded-t-lg object-cover object-center sm:w-full"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="text-lg font-bold">Branding Design</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  A comprehensive branding solution for a leading tech startup.
                </p>
              </div>
            </div>
            <div className="group relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Project</span>
              </Link>
              <img
                alt="Project 2"
                className="mx-auto aspect-video overflow-hidden rounded-t-lg object-cover object-center sm:w-full"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="text-lg font-bold">UI/UX Design</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  A sleek and intuitive user interface for a fintech app.
                </p>
              </div>
            </div>
            <div className="group relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Project</span>
              </Link>
              <img
                alt="Project 3"
                className="mx-auto aspect-video overflow-hidden rounded-t-lg object-cover object-center sm:w-full"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="text-lg font-bold">Packaging Design</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  A modern and sustainable packaging design for a luxury brand.
                </p>
              </div>
            </div>
            <div className="group relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Project</span>
              </Link>
              <img
                alt="Project 4"
                className="mx-auto aspect-video overflow-hidden rounded-t-lg object-cover object-center sm:w-full"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="text-lg font-bold">Web Design</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  A modern and responsive website design for a creative agency.
                </p>
              </div>
            </div>
            <div className="group relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Project</span>
              </Link>
              <img
                alt="Project 5"
                className="mx-auto aspect-video overflow-hidden rounded-t-lg object-cover object-center sm:w-full"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="text-lg font-bold">Mobile App Design</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  A visually stunning and intuitive mobile app design for a fitness platform.
                </p>
              </div>
            </div>
            <div className="group relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Project</span>
              </Link>
              <img
                alt="Project 6"
                className="mx-auto aspect-video overflow-hidden rounded-t-lg object-cover object-center sm:w-full"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="text-lg font-bold">Illustration Design</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  A series of whimsical illustrations for a children's book.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">About Sophia</h2>
            <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Sophia is a highly skilled and award-winning graphic designer with over 10 years of experience in the
              industry. She is passionate about creating visually stunning and user-centric designs that captivate and
              inspire.
            </p>
            <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              With a keen eye for detail and a deep understanding of design principles, Sophia has worked with a diverse
              range of clients, from startups to established brands, to bring their visions to life. Her portfolio
              showcases her versatility and expertise across various design disciplines, including branding, UI/UX,
              packaging, and illustration.
            </p>
          </div>
          <img
            alt="Sophia"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            height="550"
            src="/placeholder.svg"
            width="550"
          />
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 border-t">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Get in Touch</h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Have a project in mind or want to learn more about Sophia's services? Fill out the form below, and she'll
              be in touch.
            </p>
          </div>
          <div className="mx-auto w-full max-w-sm space-y-2">
            <form className="flex flex-col space-y-2">
              <Input className="max-w-lg flex-1" placeholder="Name" type="text" />
              <Input className="max-w-lg flex-1" placeholder="Email" type="email" />
              <Textarea className="max-w-lg flex-1" placeholder="Message" />
              <Button type="submit">Submit</Button>
            </form>
          </div>
        </div>
      </section>
    </main>
  )
}
